//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public string HN { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Fullname { get; set; }
        public string CardID { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string MobileNumber { get; set; }
        public string FullAddress { get; set; }
        public string Symptom { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> NurseFirstID { get; set; }
        public Nullable<int> NurseSecondID { get; set; }
        public Nullable<int> NurseThirthID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<bool> IsNewCase { get; set; }
        public Nullable<bool> IsFollowCase { get; set; }
        public Nullable<bool> OPD { get; set; }
        public Nullable<bool> IPD { get; set; }
        public Nullable<bool> EndoscopicCheck { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> EndoscopicID { get; set; }
    }
}
