//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindingCystoscope
    {
        public int FindingID { get; set; }
        public int EndoscopicID { get; set; }
        public Nullable<int> PrincipalProcedureID { get; set; }
        public string PrincipalProcedureDetail { get; set; }
        public Nullable<int> SupplementalProcedure1ID { get; set; }
        public string SupplementalProcedure1Detail { get; set; }
        public Nullable<int> SupplementalProcedure2ID { get; set; }
        public string SupplementalProcedure2Detail { get; set; }
        public string Procedure { get; set; }
        public Nullable<int> DxID1 { get; set; }
        public string DxID1Detail { get; set; }
        public Nullable<int> DxID2 { get; set; }
        public string DxID2Detail { get; set; }
        public Nullable<int> DxID3 { get; set; }
        public string DxID3Detail { get; set; }
        public string Complication { get; set; }
        public string Histopathology { get; set; }
        public string Recommendation { get; set; }
        public string Comment { get; set; }
        public string Urethra { get; set; }
        public string Prostate { get; set; }
        public string BladderNeck { get; set; }
        public string TrigoneandOrifices { get; set; }
        public string Bladder { get; set; }
        public string UreterRight { get; set; }
        public string UreterLeft { get; set; }
        public string KidneyRight { get; set; }
        public string KidneyLeft { get; set; }
        public string Other { get; set; }
    }
}
