//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistorieID { get; set; }
        public Nullable<int> EndoscopicID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public string Symptom { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public bool IsActive { get; set; }
    }
}
