//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingDevice
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string AspectRatio { get; set; }
        public Nullable<int> RatioX { get; set; }
        public Nullable<int> RatioY { get; set; }
        public string PositionCrop { get; set; }
        public Nullable<int> CrpX { get; set; }
        public Nullable<int> CrpY { get; set; }
        public Nullable<int> CrpWidth { get; set; }
        public Nullable<int> CrpHeight { get; set; }
        public Nullable<int> Instrument1ID { get; set; }
        public Nullable<int> Instrument2ID { get; set; }
    }
}
