//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciman
    {
        public int SpecimenID { get; set; }
        public Nullable<bool> BalAt { get; set; }
        public string BalAtDetail { get; set; }
        public Nullable<bool> BalAtCytho { get; set; }
        public Nullable<bool> BalAtPatho { get; set; }
        public Nullable<bool> BalAtGram { get; set; }
        public Nullable<bool> BalAtAFB { get; set; }
        public Nullable<bool> BalAtModAFB { get; set; }
        public Nullable<bool> BrushingAt { get; set; }
        public string BrushingAtDetail { get; set; }
        public Nullable<bool> BrushingAtCytho { get; set; }
        public Nullable<bool> BrushingAtPatho { get; set; }
        public Nullable<bool> BrushingAtGram { get; set; }
        public Nullable<bool> BrushingAtAFB { get; set; }
        public Nullable<bool> BrushingAtModAFB { get; set; }
        public Nullable<bool> EndoproncialBiopsyAt { get; set; }
        public string EndoproncialBiopsyAtDetail { get; set; }
        public Nullable<bool> EndoproncialBiopsyAtCytho { get; set; }
        public Nullable<bool> EndoproncialBiopsyAtPatho { get; set; }
        public Nullable<bool> EndoproncialBiopsyAtGram { get; set; }
        public Nullable<bool> EndoproncialBiopsyAtAFB { get; set; }
        public Nullable<bool> EndoproncialBiopsyAtModAFB { get; set; }
        public Nullable<bool> TransbroncialBiopsyAt { get; set; }
        public string TransbroncialBiopsyAtDetail { get; set; }
        public Nullable<bool> TransbroncialBiopsyAtCytho { get; set; }
        public Nullable<bool> TransbroncialBiopsyAtPatho { get; set; }
        public Nullable<bool> TransbroncialBiopsyAtGram { get; set; }
        public Nullable<bool> TransbroncialBiopsyAtAFB { get; set; }
        public Nullable<bool> TransbroncialBiopsyAtModAFB { get; set; }
        public Nullable<bool> Transbroncial { get; set; }
        public string TransbroncialDetail { get; set; }
        public Nullable<bool> TransbroncialCytho { get; set; }
        public Nullable<bool> TransbroncialPatho { get; set; }
        public Nullable<bool> TransbroncialGram { get; set; }
        public Nullable<bool> TransbroncialAFB { get; set; }
        public Nullable<bool> TransbroncialModAFB { get; set; }
        public Nullable<bool> BiopsyforPathological { get; set; }
        public Nullable<bool> BiopsyforCLOTest { get; set; }
        public Nullable<bool> BiopsyforCLOTestResult { get; set; }
        public Nullable<bool> Positive { get; set; }
        public Nullable<bool> Nagative { get; set; }
        public string OtherDetail1 { get; set; }
        public string OtherDetail2 { get; set; }
        public string OtherDetail3 { get; set; }
        public string OtherDetail4 { get; set; }
        public string OtherDetail5 { get; set; }
    }
}
