//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Fullname { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> AspectRatioID { get; set; }
        public Nullable<int> RatioX { get; set; }
        public Nullable<int> RatioY { get; set; }
        public string PositionCrop { get; set; }
        public Nullable<int> CrpX { get; set; }
        public Nullable<int> CrpY { get; set; }
        public Nullable<int> CrpWidth { get; set; }
        public Nullable<int> CrpHeight { get; set; }
    }
}
