//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndoscopicSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AppointmentDetails
    {
        public int AppointmentID { get; set; }
        public string HN { get; set; }
        public string Fullname { get; set; }
        public string Symptom { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public string ProcedureName { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string EndoscopicRoom { get; set; }
        public string Doctor { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<bool> EndoscopicCheck { get; set; }
        public Nullable<int> EndoscopicID { get; set; }
    }
}
